<?php

namespace App\Tests\Unit\Common\Spotify\Client;

use App\Common\Spotify\Client\SpotifyClient;
use App\Common\Spotify\DTO\TokenDto;
use App\Common\Spotify\Exception\UnauthorizedException;
use PHPUnit\Framework\Attributes\TestWith;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Contracts\HttpClient\ResponseInterface;

final class SpotifyClientTest extends TestCase
{
    private SpotifyClient $spotifyClient;
    private HttpClientInterface|MockObject $httpClientMock;

    private ResponseInterface|MockObject $responseMock;

    protected function setUp(): void
    {
        $this->httpClientMock = $this->createMock(HttpClientInterface::class);
        $this->spotifyClient = new SpotifyClient(
            $this->httpClientMock,
            'client_id',
            'client_secret',
            'redirect_uri'
        );
        $this->responseMock = $this->createMock(ResponseInterface::class);
    }

    public function testGetToken(): void
    {
        $code = 'dummy-code';
        $responseBody = [
            'access_token' => 'tokenTest',
             'token_type' => 'typeTest',
             'expires_in' => 999999999,
             'scope' => 'scopeTest',
             'refresh_token' => 'refreshToken',
        ];

        \assert($this->responseMock instanceof MockObject);
        $this->responseMock->method('toArray')->willReturn($responseBody);

        \assert($this->httpClientMock instanceof MockObject);
        $this->httpClientMock->expects($this->once())
            ->method('request')
            ->with(
                $this->equalTo('POST'),
                $this->equalTo(SpotifyClient::TOKEN_URI),
                $this->callback(function ($options) use ($code) {
                    $this->assertEquals('Basic '.base64_encode('client_id:client_secret'), $options['headers']['Authorization']);
                    $this->assertEquals('redirect_uri', $options['body']['redirect_uri']);
                    $this->assertEquals($code, $options['body']['code']);

                    return true;
                })
            )
            ->willReturn($this->responseMock);

        $tokenDto = $this->spotifyClient->getToken($code);

        $this->assertInstanceOf(TokenDto::class, $tokenDto);
        $this->assertEquals('tokenTest', $tokenDto->accessToken);
        $this->assertEquals('typeTest', $tokenDto->type);
        $this->assertEquals('refreshToken', $tokenDto->refreshToken);
        $this->assertEquals('scopeTest', $tokenDto->scope);
        $this->assertEquals(999999999, $tokenDto->expiredIn);
    }

    public function testGetTokenFromRefreshToken(): void
    {
        $refreshToken = 'refreshToken';
        $responseBody = [
            'access_token' => 'tokenTest',
            'token_type' => 'typeTest',
            'expires_in' => 999999999,
            'scope' => 'scopeTest',
        ];

        \assert($this->responseMock instanceof MockObject);
        $this->responseMock->method('toArray')->willReturn($responseBody);

        \assert($this->httpClientMock instanceof MockObject);
        $this->httpClientMock->expects($this->once())
           ->method('request')
           ->with(
               $this->equalTo('POST'),
               $this->equalTo(SpotifyClient::TOKEN_URI),
               $this->callback(function ($options) use ($refreshToken) {
                   $this->assertEquals('Basic '.base64_encode('client_id:client_secret'), $options['headers']['Authorization']);
                   $this->assertEquals($refreshToken, $options['body']['refresh_token']);

                   return true;
               })
           )
            ->willReturn($this->responseMock);

        $tokenDto = $this->spotifyClient->getTokenFromRefreshToken($refreshToken);

        $this->assertInstanceOf(TokenDto::class, $tokenDto);
        $this->assertEquals('tokenTest', $tokenDto->accessToken);
        $this->assertEquals('typeTest', $tokenDto->type);
        $this->assertEquals('refreshToken', $tokenDto->refreshToken);
        $this->assertEquals('scopeTest', $tokenDto->scope);
        $this->assertEquals(999999999, $tokenDto->expiredIn);
    }

    #[TestWith(['original_url', 'https://dummy-url.com'])]
    #[TestWith(['false_key', null])]
    public function testGetUserAuthorizationUrl(string $key, ?string $url): void
    {
        $infos = [$key => 'https://dummy-url.com'];

        \assert($this->responseMock instanceof MockObject);
        $this->responseMock->method('getInfo')->willReturn($infos);

        \assert($this->httpClientMock instanceof MockObject);
        $this->httpClientMock->expects($this->once())
            ->method('request')
            ->with(
                $this->equalTo('GET'),
            )
            ->willReturn($this->responseMock);

        $response = $this->spotifyClient->getUserAuthorizationUrl();

        $this->assertEquals($url, $response);
    }

    #[TestWith([true, 'toArray'])]
    #[TestWith([false, 'getStatusCode'])]
    public function testGetRecentlyPlayedTracks(bool $isHttpStatusOk, string $responseMethod): void
    {
        $token = 'tokenTest';
        $responseBody = $isHttpStatusOk ? [
            'items' => [
                0 => [
                    'track' => [
                        'album' => [
                            'album_type' => 'album',
                            'artists' => [
                                0 => [
                                    'external_urls' => [
                                        'spotify' => 'https://open.spotify.com/artist/0ZMWrgLff357yxLyEU77a1',
                                    ],
                                    'href' => 'https://api.spotify.com/v1/artists/0ZMWrgLff357yxLyEU77a1',
                                    'id' => '0ZMWrgLff357yxLyEU77a1',
                                    'name' => 'Darren Korb',
                                    'type' => 'artist',
                                    'uri' => 'spotify:artist:0ZMWrgLff357yxLyEU77a1',
                                ],
                            ],
                            'available_markets' => [
                                0 => 'AD',
                                1 => 'AE',
                                2 => 'AG',
                                3 => 'AL',
                                4 => 'AM',
                                5 => 'AO',
                                6 => 'AR',
                                7 => 'AT',
                                8 => 'AU',
                                9 => 'AZ',
                                10 => 'BA',
                                11 => 'BB',
                                12 => 'BD',
                                13 => 'BE',
                                14 => 'BF',
                                15 => 'BG',
                                16 => 'BH',
                                17 => 'BI',
                                18 => 'BJ',
                                19 => 'BN',
                                20 => 'BO',
                                21 => 'BR',
                                22 => 'BS',
                                23 => 'BT',
                                24 => 'BW',
                                25 => 'BY',
                                26 => 'BZ',
                                27 => 'CA',
                                28 => 'CD',
                                29 => 'CG',
                                30 => 'CH',
                                31 => 'CI',
                                32 => 'CL',
                                33 => 'CM',
                                34 => 'CO',
                                35 => 'CR',
                                36 => 'CV',
                                37 => 'CW',
                                38 => 'CY',
                                39 => 'CZ',
                                40 => 'DE',
                                41 => 'DJ',
                                42 => 'DK',
                                43 => 'DM',
                                44 => 'DO',
                                45 => 'DZ',
                                46 => 'EC',
                                47 => 'EE',
                                48 => 'EG',
                                49 => 'ES',
                                50 => 'ET',
                                51 => 'FI',
                                52 => 'FJ',
                                53 => 'FM',
                                54 => 'FR',
                                55 => 'GA',
                                56 => 'GB',
                                57 => 'GD',
                                58 => 'GE',
                                59 => 'GH',
                                60 => 'GM',
                                61 => 'GN',
                                62 => 'GQ',
                                63 => 'GR',
                                64 => 'GT',
                                65 => 'GW',
                                66 => 'GY',
                                67 => 'HK',
                                68 => 'HN',
                                69 => 'HR',
                                70 => 'HT',
                                71 => 'HU',
                                72 => 'ID',
                                73 => 'IE',
                                74 => 'IL',
                                75 => 'IN',
                                76 => 'IQ',
                                77 => 'IS',
                                78 => 'IT',
                                79 => 'JM',
                                80 => 'JO',
                                81 => 'JP',
                                82 => 'KE',
                                83 => 'KG',
                                84 => 'KH',
                                85 => 'KI',
                                86 => 'KM',
                                87 => 'KN',
                                88 => 'KR',
                                89 => 'KW',
                                90 => 'KZ',
                                91 => 'LA',
                                92 => 'LB',
                                93 => 'LC',
                                94 => 'LI',
                                95 => 'LK',
                                96 => 'LR',
                                97 => 'LS',
                                98 => 'LT',
                                99 => 'LU',
                                100 => 'LV',
                                101 => 'LY',
                                102 => 'MA',
                                103 => 'MC',
                                104 => 'MD',
                                105 => 'ME',
                                106 => 'MG',
                                107 => 'MH',
                                108 => 'MK',
                                109 => 'ML',
                                110 => 'MN',
                                111 => 'MO',
                                112 => 'MR',
                                113 => 'MT',
                                114 => 'MU',
                                115 => 'MV',
                                116 => 'MW',
                                117 => 'MX',
                                118 => 'MY',
                                119 => 'MZ',
                                120 => 'NA',
                                121 => 'NE',
                                122 => 'NG',
                                123 => 'NI',
                                124 => 'NL',
                                125 => 'NO',
                                126 => 'NP',
                                127 => 'NR',
                                128 => 'NZ',
                                129 => 'OM',
                                130 => 'PA',
                                131 => 'PE',
                                132 => 'PG',
                                133 => 'PH',
                                134 => 'PK',
                                135 => 'PL',
                                136 => 'PS',
                                137 => 'PT',
                                138 => 'PW',
                                139 => 'PY',
                                140 => 'QA',
                                141 => 'RO',
                                142 => 'RS',
                                143 => 'RW',
                                144 => 'SA',
                                145 => 'SB',
                                146 => 'SC',
                                147 => 'SE',
                                148 => 'SG',
                                149 => 'SI',
                                150 => 'SK',
                                151 => 'SL',
                                152 => 'SM',
                                153 => 'SN',
                                154 => 'SR',
                                155 => 'ST',
                                156 => 'SV',
                                157 => 'SZ',
                                158 => 'TD',
                                159 => 'TG',
                                160 => 'TH',
                                161 => 'TJ',
                                162 => 'TL',
                                163 => 'TN',
                                164 => 'TO',
                                165 => 'TR',
                                166 => 'TT',
                                167 => 'TV',
                                168 => 'TW',
                                169 => 'TZ',
                                170 => 'UA',
                                171 => 'UG',
                                172 => 'US',
                                173 => 'UY',
                                174 => 'UZ',
                                175 => 'VC',
                                176 => 'VE',
                                177 => 'VN',
                                178 => 'VU',
                                179 => 'WS',
                                180 => 'XK',
                                181 => 'ZA',
                                182 => 'ZM',
                                183 => 'ZW',
                            ],
                            'external_urls' => [
                                'spotify' => 'https://open.spotify.com/album/5jTYZA6b4VoSRnR5TMldgb',
                            ],
                            'href' => 'https://api.spotify.com/v1/albums/5jTYZA6b4VoSRnR5TMldgb',
                            'id' => '5jTYZA6b4VoSRnR5TMldgb',
                            'images' => [
                                0 => [
                                    'height' => 640,
                                    'url' => 'https://i.scdn.co/image/ab67616d0000b27310d3316d88b3123e75a24d48',
                                    'width' => 640,
                                ],
                                1 => [
                                    'height' => 300,
                                    'url' => 'https://i.scdn.co/image/ab67616d00001e0210d3316d88b3123e75a24d48',
                                    'width' => 300,
                                ],
                                2 => [
                                    'height' => 64,
                                    'url' => 'https://i.scdn.co/image/ab67616d0000485110d3316d88b3123e75a24d48',
                                    'width' => 64,
                                ],
                            ],
                            'name' => 'Hades: Original Soundtrack',
                            'release_date' => '2020-09-16',
                            'release_date_precision' => 'day',
                            'total_tracks' => 30,
                            'type' => 'album',
                            'uri' => 'spotify:album:5jTYZA6b4VoSRnR5TMldgb',
                        ],
                        'artists' => [
                            0 => [
                                'external_urls' => [
                                    'spotify' => 'https://open.spotify.com/artist/0ZMWrgLff357yxLyEU77a1',
                                ],
                                'href' => 'https://api.spotify.com/v1/artists/0ZMWrgLff357yxLyEU77a1',
                                'id' => '0ZMWrgLff357yxLyEU77a1',
                                'name' => 'Darren Korb',
                                'type' => 'artist',
                                'uri' => 'spotify:artist:0ZMWrgLff357yxLyEU77a1',
                            ],
                        ],
                        'available_markets' => [
                            0 => 'AR',
                            1 => 'AU',
                            2 => 'AT',
                            3 => 'BE',
                            4 => 'BO',
                            5 => 'BR',
                            6 => 'BG',
                            7 => 'CA',
                            8 => 'CL',
                            9 => 'CO',
                            10 => 'CR',
                            11 => 'CY',
                            12 => 'CZ',
                            13 => 'DK',
                            14 => 'DO',
                            15 => 'DE',
                            16 => 'EC',
                            17 => 'EE',
                            18 => 'SV',
                            19 => 'FI',
                            20 => 'FR',
                            21 => 'GR',
                            22 => 'GT',
                            23 => 'HN',
                            24 => 'HK',
                            25 => 'HU',
                            26 => 'IS',
                            27 => 'IE',
                            28 => 'IT',
                            29 => 'LV',
                            30 => 'LT',
                            31 => 'LU',
                            32 => 'MY',
                            33 => 'MT',
                            34 => 'MX',
                            35 => 'NL',
                            36 => 'NZ',
                            37 => 'NI',
                            38 => 'NO',
                            39 => 'PA',
                            40 => 'PY',
                            41 => 'PE',
                            42 => 'PH',
                            43 => 'PL',
                            44 => 'PT',
                            45 => 'SG',
                            46 => 'SK',
                            47 => 'ES',
                            48 => 'SE',
                            49 => 'CH',
                            50 => 'TW',
                            51 => 'TR',
                            52 => 'UY',
                            53 => 'US',
                            54 => 'GB',
                            55 => 'AD',
                            56 => 'LI',
                            57 => 'MC',
                            58 => 'ID',
                            59 => 'JP',
                            60 => 'TH',
                            61 => 'VN',
                            62 => 'RO',
                            63 => 'IL',
                            64 => 'ZA',
                            65 => 'SA',
                            66 => 'AE',
                            67 => 'BH',
                            68 => 'QA',
                            69 => 'OM',
                            70 => 'KW',
                            71 => 'EG',
                            72 => 'MA',
                            73 => 'DZ',
                            74 => 'TN',
                            75 => 'LB',
                            76 => 'JO',
                            77 => 'PS',
                            78 => 'IN',
                            79 => 'BY',
                            80 => 'KZ',
                            81 => 'MD',
                            82 => 'UA',
                            83 => 'AL',
                            84 => 'BA',
                            85 => 'HR',
                            86 => 'ME',
                            87 => 'MK',
                            88 => 'RS',
                            89 => 'SI',
                            90 => 'KR',
                            91 => 'BD',
                            92 => 'PK',
                            93 => 'LK',
                            94 => 'GH',
                            95 => 'KE',
                            96 => 'NG',
                            97 => 'TZ',
                            98 => 'UG',
                            99 => 'AG',
                            100 => 'AM',
                            101 => 'BS',
                            102 => 'BB',
                            103 => 'BZ',
                            104 => 'BT',
                            105 => 'BW',
                            106 => 'BF',
                            107 => 'CV',
                            108 => 'CW',
                            109 => 'DM',
                            110 => 'FJ',
                            111 => 'GM',
                            112 => 'GE',
                            113 => 'GD',
                            114 => 'GW',
                            115 => 'GY',
                            116 => 'HT',
                            117 => 'JM',
                            118 => 'KI',
                            119 => 'LS',
                            120 => 'LR',
                            121 => 'MW',
                            122 => 'MV',
                            123 => 'ML',
                            124 => 'MH',
                            125 => 'FM',
                            126 => 'NA',
                            127 => 'NR',
                            128 => 'NE',
                            129 => 'PW',
                            130 => 'PG',
                            131 => 'WS',
                            132 => 'SM',
                            133 => 'ST',
                            134 => 'SN',
                            135 => 'SC',
                            136 => 'SL',
                            137 => 'SB',
                            138 => 'KN',
                            139 => 'LC',
                            140 => 'VC',
                            141 => 'SR',
                            142 => 'TL',
                            143 => 'TO',
                            144 => 'TT',
                            145 => 'TV',
                            146 => 'VU',
                            147 => 'AZ',
                            148 => 'BN',
                            149 => 'BI',
                            150 => 'KH',
                            151 => 'CM',
                            152 => 'TD',
                            153 => 'KM',
                            154 => 'GQ',
                            155 => 'SZ',
                            156 => 'GA',
                            157 => 'GN',
                            158 => 'KG',
                            159 => 'LA',
                            160 => 'MO',
                            161 => 'MR',
                            162 => 'MN',
                            163 => 'NP',
                            164 => 'RW',
                            165 => 'TG',
                            166 => 'UZ',
                            167 => 'ZW',
                            168 => 'BJ',
                            169 => 'MG',
                            170 => 'MU',
                            171 => 'MZ',
                            172 => 'AO',
                            173 => 'CI',
                            174 => 'DJ',
                            175 => 'ZM',
                            176 => 'CD',
                            177 => 'CG',
                            178 => 'IQ',
                            179 => 'LY',
                            180 => 'TJ',
                            181 => 'VE',
                            182 => 'ET',
                            183 => 'XK',
                        ],
                        'disc_number' => 1,
                        'duration_ms' => 541336,
                        'explicit' => false,
                        'external_ids' => [
                            'isrc' => 'TCAEJ1936744',
                        ],
                        'external_urls' => [
                            'spotify' => 'https://open.spotify.com/track/65pRSbXmrkdE1HzzIkeLPH',
                        ],
                        'href' => 'https://api.spotify.com/v1/tracks/65pRSbXmrkdE1HzzIkeLPH',
                        'id' => '65pRSbXmrkdE1HzzIkeLPH',
                        'is_local' => false,
                        'name' => 'God of the Dead',
                        'popularity' => 47,
                        'preview_url' => 'https://p.scdn.co/mp3-preview/468fabcae656d807c156cc821290be7713293a4a?cid=79eda398d82949ea8aff061c4ce75d71',
                        'track_number' => 25,
                        'type' => 'track',
                        'uri' => 'spotify:track:65pRSbXmrkdE1HzzIkeLPH',
                    ],
                    'played_at' => '2023-06-22T12:10:30.622Z',
                    'context' => null,
                ],
                1 => [
                    'track' => [
                        'album' => [
                            'album_type' => 'single',
                            'artists' => [
                                0 => [
                                    'external_urls' => [
                                        'spotify' => 'https://open.spotify.com/artist/37Kwz8lKQipujhPpz9Q5cQ',
                                    ],
                                    'href' => 'https://api.spotify.com/v1/artists/37Kwz8lKQipujhPpz9Q5cQ',
                                    'id' => '37Kwz8lKQipujhPpz9Q5cQ',
                                    'name' => 'Rafferty',
                                    'type' => 'artist',
                                    'uri' => 'spotify:artist:37Kwz8lKQipujhPpz9Q5cQ',
                                ],
                            ],
                            'available_markets' => [
                                0 => 'AD',
                                1 => 'AE',
                                2 => 'AG',
                                3 => 'AM',
                                4 => 'AO',
                                5 => 'AR',
                                6 => 'AT',
                                7 => 'AU',
                                8 => 'AZ',
                                9 => 'BB',
                                10 => 'BD',
                                11 => 'BE',
                                12 => 'BF',
                                13 => 'BG',
                                14 => 'BH',
                                15 => 'BI',
                                16 => 'BJ',
                                17 => 'BN',
                                18 => 'BO',
                                19 => 'BR',
                                20 => 'BS',
                                21 => 'BT',
                                22 => 'BW',
                                23 => 'BZ',
                                24 => 'CA',
                                25 => 'CG',
                                26 => 'CH',
                                27 => 'CL',
                                28 => 'CM',
                                29 => 'CO',
                                30 => 'CR',
                                31 => 'CV',
                                32 => 'CW',
                                33 => 'CY',
                                34 => 'CZ',
                                35 => 'DE',
                                36 => 'DJ',
                                37 => 'DK',
                                38 => 'DM',
                                39 => 'DO',
                                40 => 'DZ',
                                41 => 'EC',
                                42 => 'EE',
                                43 => 'EG',
                                44 => 'ES',
                                45 => 'ET',
                                46 => 'FI',
                                47 => 'FJ',
                                48 => 'FM',
                                49 => 'FR',
                                50 => 'GA',
                                51 => 'GB',
                                52 => 'GD',
                                53 => 'GE',
                                54 => 'GH',
                                55 => 'GM',
                                56 => 'GN',
                                57 => 'GQ',
                                58 => 'GR',
                                59 => 'GT',
                                60 => 'GW',
                                61 => 'GY',
                                62 => 'HK',
                                63 => 'HN',
                                64 => 'HT',
                                65 => 'HU',
                                66 => 'ID',
                                67 => 'IE',
                                68 => 'IL',
                                69 => 'IN',
                                70 => 'IS',
                                71 => 'IT',
                                72 => 'JM',
                                73 => 'JO',
                                74 => 'JP',
                                75 => 'KE',
                                76 => 'KG',
                                77 => 'KH',
                                78 => 'KI',
                                79 => 'KM',
                                80 => 'KN',
                                81 => 'KR',
                                82 => 'KW',
                                83 => 'KZ',
                                84 => 'LA',
                                85 => 'LB',
                                86 => 'LC',
                                87 => 'LI',
                                88 => 'LK',
                                89 => 'LS',
                                90 => 'LT',
                                91 => 'LU',
                                92 => 'LV',
                                93 => 'MA',
                                94 => 'MC',
                                95 => 'MD',
                                96 => 'MG',
                                97 => 'MH',
                                98 => 'ML',
                                99 => 'MN',
                                100 => 'MO',
                                101 => 'MR',
                                102 => 'MT',
                                103 => 'MU',
                                104 => 'MV',
                                105 => 'MW',
                                106 => 'MX',
                                107 => 'MY',
                                108 => 'MZ',
                                109 => 'NA',
                                110 => 'NE',
                                111 => 'NG',
                                112 => 'NI',
                                113 => 'NL',
                                114 => 'NO',
                                115 => 'NP',
                                116 => 'NR',
                                117 => 'NZ',
                                118 => 'OM',
                                119 => 'PA',
                                120 => 'PE',
                                121 => 'PG',
                                122 => 'PH',
                                123 => 'PK',
                                124 => 'PL',
                                125 => 'PS',
                                126 => 'PT',
                                127 => 'PW',
                                128 => 'PY',
                                129 => 'QA',
                                130 => 'RO',
                                131 => 'RW',
                                132 => 'SA',
                                133 => 'SB',
                                134 => 'SC',
                                135 => 'SE',
                                136 => 'SG',
                                137 => 'SI',
                                138 => 'SK',
                                139 => 'SL',
                                140 => 'SM',
                                141 => 'SN',
                                142 => 'SR',
                                143 => 'ST',
                                144 => 'SV',
                                145 => 'SZ',
                                146 => 'TD',
                                147 => 'TG',
                                148 => 'TH',
                                149 => 'TJ',
                                150 => 'TL',
                                151 => 'TN',
                                152 => 'TO',
                                153 => 'TR',
                                154 => 'TT',
                                155 => 'TV',
                                156 => 'TW',
                                157 => 'TZ',
                                158 => 'UA',
                                159 => 'UG',
                                160 => 'US',
                                161 => 'UY',
                                162 => 'UZ',
                                163 => 'VC',
                                164 => 'VE',
                                165 => 'VN',
                                166 => 'VU',
                                167 => 'WS',
                                168 => 'ZA',
                                169 => 'ZM',
                            ],
                            'external_urls' => [
                                'spotify' => 'https://open.spotify.com/album/5sxnrUJmZJ1768ZP15Oy3Q',
                            ],
                            'href' => 'https://api.spotify.com/v1/albums/5sxnrUJmZJ1768ZP15Oy3Q',
                            'id' => '5sxnrUJmZJ1768ZP15Oy3Q',
                            'images' => [
                                0 => [
                                    'height' => 640,
                                    'url' => 'https://i.scdn.co/image/ab67616d0000b273c233c9909a1d8bf8b7c2757b',
                                    'width' => 640,
                                ],
                                1 => [
                                    'height' => 300,
                                    'url' => 'https://i.scdn.co/image/ab67616d00001e02c233c9909a1d8bf8b7c2757b',
                                    'width' => 300,
                                ],
                                2 => [
                                    'height' => 64,
                                    'url' => 'https://i.scdn.co/image/ab67616d00004851c233c9909a1d8bf8b7c2757b',
                                    'width' => 64,
                                ],
                            ],
                            'name' => 'Save Me Some Sunshine',
                            'release_date' => '2016-11-30',
                            'release_date_precision' => 'day',
                            'total_tracks' => 1,
                            'type' => 'album',
                            'uri' => 'spotify:album:5sxnrUJmZJ1768ZP15Oy3Q',
                        ],
                        'artists' => [
                            0 => [
                                'external_urls' => [
                                    'spotify' => 'https://open.spotify.com/artist/37Kwz8lKQipujhPpz9Q5cQ',
                                ],
                                'href' => 'https://api.spotify.com/v1/artists/37Kwz8lKQipujhPpz9Q5cQ',
                                'id' => '37Kwz8lKQipujhPpz9Q5cQ',
                                'name' => 'Rafferty',
                                'type' => 'artist',
                                'uri' => 'spotify:artist:37Kwz8lKQipujhPpz9Q5cQ',
                            ],
                        ],
                        'available_markets' => [
                            0 => 'AR',
                            1 => 'AU',
                            2 => 'AT',
                            3 => 'BE',
                            4 => 'BO',
                            5 => 'BR',
                            6 => 'BG',
                            7 => 'CA',
                            8 => 'CL',
                            9 => 'CO',
                            10 => 'CR',
                            11 => 'CY',
                            12 => 'CZ',
                            13 => 'DK',
                            14 => 'DO',
                            15 => 'DE',
                            16 => 'EC',
                            17 => 'EE',
                            18 => 'SV',
                            19 => 'FI',
                            20 => 'FR',
                            21 => 'GR',
                            22 => 'GT',
                            23 => 'HN',
                            24 => 'HK',
                            25 => 'HU',
                            26 => 'IS',
                            27 => 'IE',
                            28 => 'IT',
                            29 => 'LV',
                            30 => 'LT',
                            31 => 'LU',
                            32 => 'MY',
                            33 => 'MT',
                            34 => 'MX',
                            35 => 'NL',
                            36 => 'NZ',
                            37 => 'NI',
                            38 => 'NO',
                            39 => 'PA',
                            40 => 'PY',
                            41 => 'PE',
                            42 => 'PH',
                            43 => 'PL',
                            44 => 'PT',
                            45 => 'SG',
                            46 => 'SK',
                            47 => 'ES',
                            48 => 'SE',
                            49 => 'CH',
                            50 => 'TW',
                            51 => 'TR',
                            52 => 'UY',
                            53 => 'US',
                            54 => 'GB',
                            55 => 'AD',
                            56 => 'LI',
                            57 => 'MC',
                            58 => 'ID',
                            59 => 'JP',
                            60 => 'TH',
                            61 => 'VN',
                            62 => 'RO',
                            63 => 'IL',
                            64 => 'ZA',
                            65 => 'SA',
                            66 => 'AE',
                            67 => 'BH',
                            68 => 'QA',
                            69 => 'OM',
                            70 => 'KW',
                            71 => 'EG',
                            72 => 'MA',
                            73 => 'DZ',
                            74 => 'TN',
                            75 => 'LB',
                            76 => 'JO',
                            77 => 'PS',
                            78 => 'IN',
                            79 => 'KZ',
                            80 => 'MD',
                            81 => 'UA',
                            82 => 'SI',
                            83 => 'KR',
                            84 => 'BD',
                            85 => 'PK',
                            86 => 'LK',
                            87 => 'GH',
                            88 => 'KE',
                            89 => 'NG',
                            90 => 'TZ',
                            91 => 'UG',
                            92 => 'AG',
                            93 => 'AM',
                            94 => 'BS',
                            95 => 'BB',
                            96 => 'BZ',
                            97 => 'BT',
                            98 => 'BW',
                            99 => 'BF',
                            100 => 'CV',
                            101 => 'CW',
                            102 => 'DM',
                            103 => 'FJ',
                            104 => 'GM',
                            105 => 'GE',
                            106 => 'GD',
                            107 => 'GW',
                            108 => 'GY',
                            109 => 'HT',
                            110 => 'JM',
                            111 => 'KI',
                            112 => 'LS',
                            113 => 'MW',
                            114 => 'MV',
                            115 => 'ML',
                            116 => 'MH',
                            117 => 'FM',
                            118 => 'NA',
                            119 => 'NR',
                            120 => 'NE',
                            121 => 'PW',
                            122 => 'PG',
                            123 => 'WS',
                            124 => 'SM',
                            125 => 'ST',
                            126 => 'SN',
                            127 => 'SC',
                            128 => 'SL',
                            129 => 'SB',
                            130 => 'KN',
                            131 => 'LC',
                            132 => 'VC',
                            133 => 'SR',
                            134 => 'TL',
                            135 => 'TO',
                            136 => 'TT',
                            137 => 'TV',
                            138 => 'VU',
                            139 => 'AZ',
                            140 => 'BN',
                            141 => 'BI',
                            142 => 'KH',
                            143 => 'CM',
                            144 => 'TD',
                            145 => 'KM',
                            146 => 'GQ',
                            147 => 'SZ',
                            148 => 'GA',
                            149 => 'GN',
                            150 => 'KG',
                            151 => 'LA',
                            152 => 'MO',
                            153 => 'MR',
                            154 => 'MN',
                            155 => 'NP',
                            156 => 'RW',
                            157 => 'TG',
                            158 => 'UZ',
                            159 => 'BJ',
                            160 => 'MG',
                            161 => 'MU',
                            162 => 'MZ',
                            163 => 'AO',
                            164 => 'DJ',
                            165 => 'ZM',
                            166 => 'CG',
                            167 => 'TJ',
                            168 => 'VE',
                            169 => 'ET',
                        ],
                        'disc_number' => 1,
                        'duration_ms' => 217143,
                        'explicit' => false,
                        'external_ids' => [
                            'isrc' => 'TCACT1652450',
                        ],
                        'external_urls' => [
                            'spotify' => 'https://open.spotify.com/track/68vTrjlrczwHWioLZ5p0Rt',
                        ],
                        'href' => 'https://api.spotify.com/v1/tracks/68vTrjlrczwHWioLZ5p0Rt',
                        'id' => '68vTrjlrczwHWioLZ5p0Rt',
                        'is_local' => false,
                        'name' => 'Save Me Some Sunshine',
                        'popularity' => 49,
                        'preview_url' => 'https://p.scdn.co/mp3-preview/593289a29a600675300bb76bee7dd7db187a7583?cid=79eda398d82949ea8aff061c4ce75d71',
                        'track_number' => 1,
                        'type' => 'track',
                        'uri' => 'spotify:track:68vTrjlrczwHWioLZ5p0Rt',
                    ],
                    'played_at' => '2023-06-15T13:38:11.726Z',
                    'context' => null,
                ],
                2 => [
                    'track' => [
                        'album' => [
                            'album_type' => 'album',
                            'artists' => [
                                0 => [
                                    'external_urls' => [
                                        'spotify' => 'https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4',
                                    ],
                                    'href' => 'https://api.spotify.com/v1/artists/23fqKkggKUBHNkbKtXEls4',
                                    'id' => '23fqKkggKUBHNkbKtXEls4',
                                    'name' => 'Kygo',
                                    'type' => 'artist',
                                    'uri' => 'spotify:artist:23fqKkggKUBHNkbKtXEls4',
                                ],
                            ],
                            'available_markets' => [
                                0 => 'AD',
                                1 => 'AE',
                                2 => 'AG',
                                3 => 'AL',
                                4 => 'AM',
                                5 => 'AO',
                                6 => 'AR',
                                7 => 'AT',
                                8 => 'AU',
                                9 => 'AZ',
                                10 => 'BA',
                                11 => 'BB',
                                12 => 'BD',
                                13 => 'BE',
                                14 => 'BF',
                                15 => 'BG',
                                16 => 'BH',
                                17 => 'BI',
                                18 => 'BJ',
                                19 => 'BN',
                                20 => 'BO',
                                21 => 'BR',
                                22 => 'BS',
                                23 => 'BT',
                                24 => 'BW',
                                25 => 'BY',
                                26 => 'BZ',
                                27 => 'CA',
                                28 => 'CD',
                                29 => 'CG',
                                30 => 'CH',
                                31 => 'CI',
                                32 => 'CL',
                                33 => 'CM',
                                34 => 'CO',
                                35 => 'CR',
                                36 => 'CV',
                                37 => 'CW',
                                38 => 'CY',
                                39 => 'CZ',
                                40 => 'DE',
                                41 => 'DJ',
                                42 => 'DK',
                                43 => 'DM',
                                44 => 'DO',
                                45 => 'DZ',
                                46 => 'EC',
                                47 => 'EE',
                                48 => 'EG',
                                49 => 'ES',
                                50 => 'ET',
                                51 => 'FI',
                                52 => 'FJ',
                                53 => 'FM',
                                54 => 'FR',
                                55 => 'GA',
                                56 => 'GB',
                                57 => 'GD',
                                58 => 'GE',
                                59 => 'GH',
                                60 => 'GM',
                                61 => 'GN',
                                62 => 'GQ',
                                63 => 'GR',
                                64 => 'GT',
                                65 => 'GW',
                                66 => 'GY',
                                67 => 'HK',
                                68 => 'HN',
                                69 => 'HR',
                                70 => 'HT',
                                71 => 'HU',
                                72 => 'ID',
                                73 => 'IE',
                                74 => 'IL',
                                75 => 'IN',
                                76 => 'IQ',
                                77 => 'IS',
                                78 => 'IT',
                                79 => 'JM',
                                80 => 'JO',
                                81 => 'JP',
                                82 => 'KE',
                                83 => 'KG',
                                84 => 'KH',
                                85 => 'KI',
                                86 => 'KM',
                                87 => 'KN',
                                88 => 'KR',
                                89 => 'KW',
                                90 => 'KZ',
                                91 => 'LA',
                                92 => 'LB',
                                93 => 'LC',
                                94 => 'LI',
                                95 => 'LK',
                                96 => 'LR',
                                97 => 'LS',
                                98 => 'LT',
                                99 => 'LU',
                                100 => 'LV',
                                101 => 'LY',
                                102 => 'MA',
                                103 => 'MC',
                                104 => 'MD',
                                105 => 'ME',
                                106 => 'MG',
                                107 => 'MH',
                                108 => 'MK',
                                109 => 'ML',
                                110 => 'MN',
                                111 => 'MO',
                                112 => 'MR',
                                113 => 'MT',
                                114 => 'MU',
                                115 => 'MV',
                                116 => 'MW',
                                117 => 'MX',
                                118 => 'MY',
                                119 => 'MZ',
                                120 => 'NA',
                                121 => 'NE',
                                122 => 'NG',
                                123 => 'NI',
                                124 => 'NL',
                                125 => 'NO',
                                126 => 'NP',
                                127 => 'NR',
                                128 => 'NZ',
                                129 => 'OM',
                                130 => 'PA',
                                131 => 'PE',
                                132 => 'PG',
                                133 => 'PH',
                                134 => 'PK',
                                135 => 'PL',
                                136 => 'PS',
                                137 => 'PT',
                                138 => 'PW',
                                139 => 'PY',
                                140 => 'QA',
                                141 => 'RO',
                                142 => 'RS',
                                143 => 'RW',
                                144 => 'SA',
                                145 => 'SB',
                                146 => 'SC',
                                147 => 'SE',
                                148 => 'SG',
                                149 => 'SI',
                                150 => 'SK',
                                151 => 'SL',
                                152 => 'SM',
                                153 => 'SN',
                                154 => 'SR',
                                155 => 'ST',
                                156 => 'SV',
                                157 => 'SZ',
                                158 => 'TD',
                                159 => 'TG',
                                160 => 'TH',
                                161 => 'TJ',
                                162 => 'TL',
                                163 => 'TN',
                                164 => 'TO',
                                165 => 'TR',
                                166 => 'TT',
                                167 => 'TV',
                                168 => 'TW',
                                169 => 'TZ',
                                170 => 'UA',
                                171 => 'UG',
                                172 => 'US',
                                173 => 'UY',
                                174 => 'UZ',
                                175 => 'VC',
                                176 => 'VE',
                                177 => 'VN',
                                178 => 'VU',
                                179 => 'WS',
                                180 => 'XK',
                                181 => 'ZA',
                                182 => 'ZM',
                                183 => 'ZW',
                            ],
                            'external_urls' => [
                                'spotify' => 'https://open.spotify.com/album/7tcs1X9pzFvcLOPuhCstQJ',
                            ],
                            'href' => 'https://api.spotify.com/v1/albums/7tcs1X9pzFvcLOPuhCstQJ',
                            'id' => '7tcs1X9pzFvcLOPuhCstQJ',
                            'images' => [
                                0 => [
                                    'height' => 640,
                                    'url' => 'https://i.scdn.co/image/ab67616d0000b27380368f0aa8f90c51674f9dd2',
                                    'width' => 640,
                                ],
                                1 => [
                                    'height' => 300,
                                    'url' => 'https://i.scdn.co/image/ab67616d00001e0280368f0aa8f90c51674f9dd2',
                                    'width' => 300,
                                ],
                                2 => [
                                    'height' => 64,
                                    'url' => 'https://i.scdn.co/image/ab67616d0000485180368f0aa8f90c51674f9dd2',
                                    'width' => 64,
                                ],
                            ],
                            'name' => 'Golden Hour',
                            'release_date' => '2020-05-29',
                            'release_date_precision' => 'day',
                            'total_tracks' => 18,
                            'type' => 'album',
                            'uri' => 'spotify:album:7tcs1X9pzFvcLOPuhCstQJ',
                        ],
                        'artists' => [
                            0 => [
                                'external_urls' => [
                                    'spotify' => 'https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4',
                                ],
                                'href' => 'https://api.spotify.com/v1/artists/23fqKkggKUBHNkbKtXEls4',
                                'id' => '23fqKkggKUBHNkbKtXEls4',
                                'name' => 'Kygo',
                                'type' => 'artist',
                                'uri' => 'spotify:artist:23fqKkggKUBHNkbKtXEls4',
                            ],
                            1 => [
                                'external_urls' => [
                                    'spotify' => 'https://open.spotify.com/artist/2FsZnS8gQ8jG1HGnPYNlm9',
                                ],
                                'href' => 'https://api.spotify.com/v1/artists/2FsZnS8gQ8jG1HGnPYNlm9',
                                'id' => '2FsZnS8gQ8jG1HGnPYNlm9',
                                'name' => 'Jamie N Commons',
                                'type' => 'artist',
                                'uri' => 'spotify:artist:2FsZnS8gQ8jG1HGnPYNlm9',
                            ],
                        ],
                        'available_markets' => [
                            0 => 'AR',
                            1 => 'AU',
                            2 => 'AT',
                            3 => 'BE',
                            4 => 'BO',
                            5 => 'BR',
                            6 => 'BG',
                            7 => 'CA',
                            8 => 'CL',
                            9 => 'CO',
                            10 => 'CR',
                            11 => 'CY',
                            12 => 'CZ',
                            13 => 'DK',
                            14 => 'DO',
                            15 => 'DE',
                            16 => 'EC',
                            17 => 'EE',
                            18 => 'SV',
                            19 => 'FI',
                            20 => 'FR',
                            21 => 'GR',
                            22 => 'GT',
                            23 => 'HN',
                            24 => 'HK',
                            25 => 'HU',
                            26 => 'IS',
                            27 => 'IE',
                            28 => 'IT',
                            29 => 'LV',
                            30 => 'LT',
                            31 => 'LU',
                            32 => 'MY',
                            33 => 'MT',
                            34 => 'MX',
                            35 => 'NL',
                            36 => 'NZ',
                            37 => 'NI',
                            38 => 'NO',
                            39 => 'PA',
                            40 => 'PY',
                            41 => 'PE',
                            42 => 'PH',
                            43 => 'PL',
                            44 => 'PT',
                            45 => 'SG',
                            46 => 'SK',
                            47 => 'ES',
                            48 => 'SE',
                            49 => 'CH',
                            50 => 'TW',
                            51 => 'TR',
                            52 => 'UY',
                            53 => 'US',
                            54 => 'GB',
                            55 => 'AD',
                            56 => 'LI',
                            57 => 'MC',
                            58 => 'ID',
                            59 => 'JP',
                            60 => 'TH',
                            61 => 'VN',
                            62 => 'RO',
                            63 => 'IL',
                            64 => 'ZA',
                            65 => 'SA',
                            66 => 'AE',
                            67 => 'BH',
                            68 => 'QA',
                            69 => 'OM',
                            70 => 'KW',
                            71 => 'EG',
                            72 => 'MA',
                            73 => 'DZ',
                            74 => 'TN',
                            75 => 'LB',
                            76 => 'JO',
                            77 => 'PS',
                            78 => 'IN',
                            79 => 'BY',
                            80 => 'KZ',
                            81 => 'MD',
                            82 => 'UA',
                            83 => 'AL',
                            84 => 'BA',
                            85 => 'HR',
                            86 => 'ME',
                            87 => 'MK',
                            88 => 'RS',
                            89 => 'SI',
                            90 => 'KR',
                            91 => 'BD',
                            92 => 'PK',
                            93 => 'LK',
                            94 => 'GH',
                            95 => 'KE',
                            96 => 'NG',
                            97 => 'TZ',
                            98 => 'UG',
                            99 => 'AG',
                            100 => 'AM',
                            101 => 'BS',
                            102 => 'BB',
                            103 => 'BZ',
                            104 => 'BT',
                            105 => 'BW',
                            106 => 'BF',
                            107 => 'CV',
                            108 => 'CW',
                            109 => 'DM',
                            110 => 'FJ',
                            111 => 'GM',
                            112 => 'GE',
                            113 => 'GD',
                            114 => 'GW',
                            115 => 'GY',
                            116 => 'HT',
                            117 => 'JM',
                            118 => 'KI',
                            119 => 'LS',
                            120 => 'LR',
                            121 => 'MW',
                            122 => 'MV',
                            123 => 'ML',
                            124 => 'MH',
                            125 => 'FM',
                            126 => 'NA',
                            127 => 'NR',
                            128 => 'NE',
                            129 => 'PW',
                            130 => 'PG',
                            131 => 'WS',
                            132 => 'SM',
                            133 => 'ST',
                            134 => 'SN',
                            135 => 'SC',
                            136 => 'SL',
                            137 => 'SB',
                            138 => 'KN',
                            139 => 'LC',
                            140 => 'VC',
                            141 => 'SR',
                            142 => 'TL',
                            143 => 'TO',
                            144 => 'TT',
                            145 => 'TV',
                            146 => 'VU',
                            147 => 'AZ',
                            148 => 'BN',
                            149 => 'BI',
                            150 => 'KH',
                            151 => 'CM',
                            152 => 'TD',
                            153 => 'KM',
                            154 => 'GQ',
                            155 => 'SZ',
                            156 => 'GA',
                            157 => 'GN',
                            158 => 'KG',
                            159 => 'LA',
                            160 => 'MO',
                            161 => 'MR',
                            162 => 'MN',
                            163 => 'NP',
                            164 => 'RW',
                            165 => 'TG',
                            166 => 'UZ',
                            167 => 'ZW',
                            168 => 'BJ',
                            169 => 'MG',
                            170 => 'MU',
                            171 => 'MZ',
                            172 => 'AO',
                            173 => 'CI',
                            174 => 'DJ',
                            175 => 'ZM',
                            176 => 'CD',
                            177 => 'CG',
                            178 => 'IQ',
                            179 => 'LY',
                            180 => 'TJ',
                            181 => 'VE',
                            182 => 'ET',
                            183 => 'XK',
                        ],
                        'disc_number' => 1,
                        'duration_ms' => 217246,
                        'explicit' => false,
                        'external_ids' => [
                            'isrc' => 'SEBGA2000408',
                        ],
                        'external_urls' => [
                            'spotify' => 'https://open.spotify.com/track/4B6xQy8i7cVzKT8kPIhBY5',
                        ],
                        'href' => 'https://api.spotify.com/v1/tracks/4B6xQy8i7cVzKT8kPIhBY5',
                        'id' => '4B6xQy8i7cVzKT8kPIhBY5',
                        'is_local' => false,
                        'name' => 'Feels Like Forever',
                        'popularity' => 57,
                        'preview_url' => 'https://p.scdn.co/mp3-preview/bca7c5fc043dd95687238cc0c5705946a5be882b?cid=79eda398d82949ea8aff061c4ce75d71',
                        'track_number' => 3,
                        'type' => 'track',
                        'uri' => 'spotify:track:4B6xQy8i7cVzKT8kPIhBY5',
                    ],
                    'played_at' => '2023-06-01T08:39:38.135Z',
                    'context' => [
                        'type' => 'album',
                        'href' => 'https://api.spotify.com/v1/albums/7tcs1X9pzFvcLOPuhCstQJ',
                        'external_urls' => [
                            'spotify' => 'https://open.spotify.com/album/7tcs1X9pzFvcLOPuhCstQJ',
                        ],
                        'uri' => 'spotify:album:7tcs1X9pzFvcLOPuhCstQJ',
                    ],
                ],
            ],
        ] : 401;

        \assert($this->responseMock instanceof MockObject);
        $this->responseMock->method($responseMethod)->willReturn($responseBody);

        \assert($this->httpClientMock instanceof MockObject);
        $this->httpClientMock->expects($this->once())
            ->method('request')
            ->with(
                $this->equalTo('GET'),
                $this->equalTo(SpotifyClient::RECENTLY_PLAYED_URI),
                $this->callback(function ($options) use ($token) {
                    $this->assertEquals($token, $options['auth_bearer']);

                    return true;
                })
            )
            ->willReturn($this->responseMock);

        if (false === $isHttpStatusOk) {
            $this->expectException(UnauthorizedException::class);
            $this->expectExceptionCode(Response::HTTP_UNAUTHORIZED);
        }

        $response = $this->spotifyClient->getRecentlyPlayedTracks($token);

        if (true === $isHttpStatusOk) {
            \assert(is_array($responseBody));
            $this->assertIsArray($response);
            $this->assertEquals($responseBody['items'][0]['track']['artists'][0]['name'], $response[0]->artist);
            $this->assertEquals($responseBody['items'][0]['track']['id'], $response[0]->spotifyId);
            $this->assertEquals($responseBody['items'][0]['track']['name'], $response[0]->name);
            $this->assertEquals(new \DateTime($responseBody['items'][0]['played_at']), $response[0]->playedAt);
        }
    }
}
