version: '3.8'

services:
  db:
    container_name: db_spotify
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: spotify
    ports:
      - 15432:5432

  php-fpm:
    container_name: php_spotify
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../project/:/var/www

  nginx:
    container_name: nginx_spotify
    build:
      context: ./nginx
    volumes:
      - ./../project/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"