# config/routes/attributes.yaml
controllers:
    resource:
        path: ../../src/Admin/Controller/
        namespace: App\Admin\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute