twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        client_id: '%env(CLIENT_ID)%'
        redirect_uri: '%env(REDIRECT_URI)%'

when@test:
    twig:
        strict_variables: true
